caldera_criticalmass_city_show:
    path:  /{citySlug}
    defaults: { _controller: AppBundle:City/City:show }
    options:
        expose: true

caldera_criticalmass_city_listrides:
    path:  /{citySlug}/list
    defaults: { _controller: AppBundle:City/City:listRides }

caldera_criticalmass_city_missingstats:
    path:  /{citySlug}/missingstats
    defaults: { _controller: AppBundle:City/City:missingStats }

caldera_criticalmass_city_listgalleries:
    path:  /{citySlug}/galleries
    defaults: { _controller: AppBundle:City/City:listGalleries }

caldera_criticalmass_city_locations:
    path:  /{citySlug}/locations
    defaults: { _controller: AppBundle:City/City:getlocations }
