caldera_criticalmass_track_delete:
    path:  /track/delete/{trackId}
    defaults: { _controller: AppBundle:Track/TrackManagement:delete }
    options:
        expose: true

caldera_criticalmass_track_toggle:
    path:  /track/toggle/{trackId}
    defaults: { _controller: AppBundle:Track/TrackManagement:toggle }

caldera_criticalmass_track_download:
    path:  /track/download/{trackId}
    defaults: { _controller: AppBundle:Track/TrackManagement:download }

caldera_criticalmass_track_gpxgenerate:
    path:  /track/generate/{rideId}
    defaults: { _controller: AppBundle:Track/TrackManagement:gpxgenerate }

caldera_criticalmass_track_list:
    path:  /track/list
    defaults: { _controller: AppBundle:Track/TrackManagement:list }

caldera_criticalmass_track_upload:
    path:  /{citySlug}/{rideDate}/addtrack
    defaults: { _controller: AppBundle:Track/TrackUpload:upload }

caldera_criticalmass_track_view:
    path:  /track/view/{trackId}
    defaults: { _controller: AppBundle:Track/Track:view }

caldera_criticalmass_track_range:
    path:  /track/range/{trackId}
    defaults: { _controller: AppBundle:Track/TrackRange:range }

caldera_criticalmass_track_time:
    path:  /track/time/{trackId}
    defaults: { _controller: AppBundle:Track/TrackTime:time }

caldera_criticalmass_track_draw:
    path:  /{citySlug}/{rideDate}/drawtrack
    defaults: { _controller: AppBundle:Track/TrackDraw:draw }

caldera_criticalmass_track_edit:
    path:  /track/edit/{trackId}
    defaults: { _controller: AppBundle:Track/TrackManagement:edit }
