services:
  App\Criticalmass\Image\ExifWrapper\ExifWrapper:
    arguments:
      $flysystemFilesystem: '@oneup_flysystem.flysystem_photo_photo_filesystem'

  App\Criticalmass\Image\PhotoManipulator\Storage\PhotoStorage:
    autowire: true
    arguments:
      $filesystem: '@oneup_flysystem.flysystem_photo_photo_filesystem'

  App\Criticalmass\ProfilePhotoGenerator\ProfilePhotoGenerator:
    autowire: true
    arguments:
      $filesystem: '@oneup_flysystem.flysystem_user_photo_filesystem'
      $projectDirectory: '%kernel.project_dir%'

  App\Criticalmass\UploadableDataHandler\UploadableDataHandler:
    autowire: true
    arguments:
      $filesystem: '@oneup_flysystem.flysystem_photo_photo_filesystem'

  App\Criticalmass\UploadValidator\TrackValidator:
    autowire: true
    arguments:
      $filesystem: '@oneup_flysystem.flysystem_track_track_filesystem'
