fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        criticalmass:
            client: default
            finder:
            settings:
                index:
                    analysis:
                        analyzer:
                            umlauts_analyzer:
                                type: custom
                                tokenizer: lowercase
                                filter   : [umlauts_filter]
                        filter:
                            umlauts_filter:
                                type: "asciifolding"
            types:
                ride:
                    mappings:
                        id: ~
                        title: ~
                        description: ~
                        city: { type: string, index: not_analyzed }
                        country: { type: string, index: not_analyzed }
                        location: ~
                        isArchived: ~
                        isEnabled: ~
                        dateTime: ~
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CalderaBundle\Entity\Ride
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
                city:
                    mappings:
                        id: ~
                        title: ~
                        description: ~
                        longDescription: ~
                        punchLine: ~
                        standardLocation: ~
                        isArchived: ~
                        isEnabled: ~
                        country: { type: string, index: not_analyzed }
                        pin: { type: geo_point }
                    persistence:
                        driver: orm
                        model: Caldera\Bundle\CalderaBundle\Entity\City
                        provider: ~
                        listener:
                            immediate: ~
                        finder: ~
