fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Caldera\Bundle\CalderaBundle\Entity\User #Application\Sonata\UserBundle\Entity\User
#    group:
#        group_class:   Application\Sonata\UserBundle\Entity\Group
#        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
#    service:
#        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
    registration:
        confirmation:
            enabled:    false
#            from_email:
#                address:        malte@criticalmass.in
#                sender_name:    Malte Hübner, criticalmass.in
    resetting:
        email:
            from_email:
                address:        malte@criticalmass.in
                sender_name:    Malte Hübner, criticalmass.in


fos_rest:
    view:
        formats:
            json: true
            xml: false
            html: false
            rss: false
        templating_formats:
            json: false
            xml: false
            html: false
            rss: false
        force_redirects:
            html: false
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig