caldera_radverkehrspolitik:
    resource: "@CalderaCriticalmassBlogBundle/Resources/config/routing2.yml"
    prefix:   /
    host: "%domain.radverkehrspolitik%"

caldera_criticalmassblog:
    resource: "@CalderaCriticalmassBlogBundle/Resources/config/routing.yml"
    prefix:   /
    host: "%domain.criticalmassblog%"

sonata_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

sonata_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

caldera_criticalmass_rest:
    resource: "@CalderaCriticalmassRestBundle/Resources/config/routing.yml"
    prefix:   /rest

facebook_login:
    path: /login/check-facebook

strava_login:
    path: /login/check-strava

runkeeper_login:
    path: /login/check-runkeeper

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

caldera_criticalmass:
    resource: "@CalderaCriticalmassSiteBundle/Resources/config/routing.yml"
    host: "%domain.criticalmass%"
    prefix:   /

caldera_cycleways:
    resource: "@CalderaCyclewaysBundle/Resources/config/routing.yml"
    host: "%domain.cycleways%"
    prefix:   /

caldera:
    resource: "@CalderaBundle/Resources/config/routing.yml"
    host: "%domain.caldera%"
    prefix:   /

caldera_criticalmassrocks:
    resource: "@CalderaCriticalmassRocksBundle/Resources/config/routing.yml"
    host: "%domain.criticalmassrocks%"
    prefix:   /

caldera_criticalmassphoto:
    resource: "@CalderaCriticalmassPhotoBundle/Resources/config/routing.yml"
    host: "%domain.criticalmassphoto%"
    prefix:   /

caldera_criticalmasslive:
    resource: "@CalderaCriticalmassLiveBundle/Resources/config/routing.yml"
    host: "%domain.criticalmasslive%"
    prefix:   /

