# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    memcached.server: { host: 127.0.0.1, port: 11211 }

services:
    memcached:
        # class 'Memcache' or 'Memcached', depending on which PHP module you use
        class: Memcached
        calls:
            - [ addServer, [ '127.0.0.1', 11211 ]]

    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [setMemcached, ['@memcached']]