vich_uploader:
    db_driver: orm
    
    mappings:
        track_file:
            uri_prefix:         /tracks
            upload_destination: %kernel.root_dir%/../web/tracks/
            namer:              vich_uploader.namer_uniqid

        photo_photo:
            uri_prefix:         /photos
            upload_destination: %kernel.root_dir%/../web/photos
            namer:              vich_uploader.namer_uniqid