simple_things_entity_audit:
    audited_entities:
        - App\Entity\City
        - App\Entity\CityCycle
        - App\Entity\HelpCategory
        - App\Entity\HelpItem
        - App\Entity\Location
        - App\Entity\Region
        - App\Entity\Ride
        - App\Entity\Subride
        - App\Entity\SocialNetworkProfile
        - App\Entity\SocialNetworkFeedItem
        - App\Entity\BlogPost

    global_ignore_columns:
        - created_at
        - updated_at
