simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\City
        - AppBundle\Entity\CityCycle
        - AppBundle\Entity\HelpCategory
        - AppBundle\Entity\HelpItem
        - AppBundle\Entity\Location
        - AppBundle\Entity\Region
        - AppBundle\Entity\Ride
        - AppBundle\Entity\Subride
        - AppBundle\Entity\SocialNetworkProfile
        - AppBundle\Entity\SocialNetworkFeedItem

    global_ignore_columns:
        - created_at
        - updated_at
