flagception:
    features:
        bikeright:
            default: true
        photos:
            default: true
        art11:
            default: false
        blog:
            default: true
        frontpage_advertisment:
            default: false