flagception:
    features:
        photos:
            default: true
        art11:
            default: false
        frontpage_advertisment:
            default: false
        strava_track_upload:
            default: true
        oembed:
            default: true
