overblog_graphql:
    definitions:
        schema:
            default:
                query: Query

        mappings:
            auto_discover: false
            types:
                - type: graphql
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: ~
