overblog_graphql:
    definitions:
        schema:
            query: Query
        mappings:
            auto_discover: false
            types:
                - { type: graphql, dir: "%kernel.project_dir%/config/graphql/types", suffix: null }
