###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    rabbitmq:
      image: rabbitmq
      container_name: criticalmass-rabbitmq
      labels:
        com.symfony.server.service-prefix: 'DATABASE'

    memcached:
      image: memcached:alpine
      container_name: criticalmass-memcached
      labels:
        com.symfony.server.service-prefix: 'MEMCACHED'

    redis:
      image: redis:alpine
      container_name: criticalmass-redis
      labels:
        com.symfony.server.service-prefix: 'REDIS'

    mysql:
      image: mysql:5.6
      container_name: criticalmass-mysql
      working_dir: /application
      volumes:
        - ./docker/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=criticalmass
        - MYSQL_USER=criticalmass
        - MYSQL_PASSWORD=criticalmass
      ports:
        - "8002:3306"
      labels:
        com.symfony.server.service-prefix: 'DATABASE'

    elasticsearch:
      image: elasticsearch:6.8.6
      container_name: criticalmass-elasticsearch
      environment:
        - discovery.type=single-node
      volumes:
        - ./docker/elasticsearch:/usr/share/elasticsearch/data

    webserver:
      image: nginx:alpine
      container_name: criticalmass-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: criticalmass-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

      labels:
        com.symfony.server.service-prefix: 'ELASTICSEARCH'