services:
    caldera_criticalmass.twig.extension:
        class: AppBundle\Twig\Extension\SiteTwigExtension
        arguments:
            - '@translator'
            - '@router'
            - '@critical_markdown'
        tags:
            - { name: twig.extension }

    caldera_criticalmass.twig.router_extension:
        class: AppBundle\Twig\Extension\RouterTwigExtension
        arguments:
            - '@caldera.criticalmass.routing.object_router'
        tags:
            - { name: twig.extension }

    caldera_criticalmass.twig.staticmaps:
        class: AppBundle\Twig\Extension\StaticmapsTwigExtension
        arguments:
            - '%staticmaps.host%'
        tags:
            - { name: twig.extension }
