services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $openWeatherMapApiKey: '%openweather.appid%'
            $rootDirectory: '%kernel.root_dir%'
            $projectDirectory: '%kernel.project_dir%'
            $staticmapsHost: '%staticmaps.host%'
            $featurePhotos: '%feature.photos%'
            $gapWidth: '%track.gap_width%'

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Admin,DQL,Entity,Manager,Menu,Model,Repository,Tests,UserProvider,Validator,Criticalmass/Facebook,Criticalmass/Image,Criticalmass/UploadValidator/UploadValidatorException}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Criticalmass\Image\PhotoUploader\PhotoUploader:
        arguments:
            $uploadDestinationPhoto: '%upload_destination.photo%'

    AppBundle\Criticalmass\Image\PhotoGps\PhotoGps:
        arguments:
            $uploadDestinationPhoto: '%upload_destination.photo%'

    Cmfcmf\OpenWeatherMap: ~

    AppBundle\Request\ParamConverter\RideParamConverter:
        tags:
            - { name: request.param_converter, priority: 0, converter: ride_converter }

    AppBundle\Request\ParamConverter\CityParamConverter:
        tags:
            - { name: request.param_converter, priority: 0, converter: city_converter }

    AppBundle\Request\ParamConverter\LocationParamConverter:
        tags:
            - { name: request.param_converter, priority: 0, converter: location_converter }

    AppBundle\Request\ParamConverter\BoardParamConverter:
        tags:
            - { name: request.param_converter, priority: 0, converter: board_converter }

    AppBundle\Request\ParamConverter\ThreadParamConverter:
        tags:
            - { name: request.param_converter, priority: 0, converter: thread_converter }

    AppBundle\Request\ParamConverter\PhotoParamConverter:
        tags:
            - { name: request.param_converter, priority: 0, converter: photo_converter }

    AppBundle\Request\ParamConverter\UserParamConverter:
        tags:
            - { name: request.param_converter, priority: 10, converter: user_converter }
