caldera_criticalmass_rest_ride_list:
    path:     /ride
    defaults: { _controller: AppBundle:Api/Ride:list }
    methods:  [GET]

caldera_criticalmass_rest_ride_list_deprecated:
    path:     /ride/list
    defaults: { _controller: AppBundle:Api/Ride:list }
    methods:  [GET]

caldera_criticalmass_rest_city_list:
    path:     /city
    defaults: { _controller: AppBundle:Api/City:list }
    methods:  [GET]

caldera_criticalmass_rest_city_list_deprecated:
    path:     /city/list
    defaults: { _controller: AppBundle:Api/City:list }
    methods:  [GET]

caldera_criticalmass_rest_photo_gallery:
    path:     /photo/gallery
    defaults: { _controller: AppBundle:Api/Photo:gallery }
    methods:  [GET]

caldera_criticalmass_rest_city_show:
    path:     /{citySlug}
    defaults: { _controller: AppBundle:Api/City:show }
    methods:  [GET]

caldera_criticalmass_rest_ride_show_current:
    path:     /{citySlug}/current
    defaults: { _controller: AppBundle:Api/Ride:showCurrent }
    methods:  [GET]

caldera_criticalmass_rest_ride_show:
    path:     /{citySlug}/{rideDate}
    defaults: { _controller: AppBundle:Api/Ride:show }
    methods:  [GET]

caldera_criticalmass_rest_estimate_create:
    path:     /estimate
    defaults: { _controller: AppBundle:Api/Estimate:create }
    methods:  [POST]
