caldera_criticalmass_citycycle_list:
    path:  /{citySlug}/cycles/list
    defaults: { _controller: AppBundle:City/CityCycle:list }

caldera_criticalmass_citycycle_add:
    path:  /{citySlug}/cycles/add
    defaults: { _controller: AppBundle:City/CityCycle:add }

caldera_criticalmass_citycycle_edit:
    path:  /{citySlug}/cycles/{cycleId}/edit
    defaults: { _controller: AppBundle:City/CityCycle:edit }

caldera_criticalmass_citycycle_disable:
    path:  /{citySlug}/cycles/{cycleId}/disable
    defaults: { _controller: AppBundle:City/CityCycle:disable }
