caldera_criticalmass_help_index:
    path:     /help
    defaults: { _controller: AppBundle:Help:help }

caldera_criticalmass_help_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Help:faq }

caldera_criticalmass_help_about:
    path:     /about
    defaults: { _controller: AppBundle:Help:about }
