caldera_criticalmass_ride_show:
    path:  /{citySlug}/{rideDate}
    defaults: { _controller: AppBundle:Ride/Ride:show }
    requirements:
        rideDate: '([0-9]{4,4})\-([0-9]{2,2})\-([0-9]{1,2})'
    options:
        expose: true

caldera_criticalmass_ride_show_month:
    path:  /{citySlug}/{rideDate}
    defaults: { _controller: AppBundle:Ride/Ride:show }
    requirements:
        rideDate: '([0-9]{4,4})\-([0-9]{2,2})'
    options:
        expose: true
