caldera_criticalmass_statistic_city:
    path: /{citySlug}/statistic
    defaults: { _controller: AppBundle:Statistic/Statistic:citystatistic }

caldera_criticalmass_statistic_overview:
    path: /statistic
    defaults: { _controller: AppBundle:Statistic/Statistic:overview }

caldera_criticalmass_statistic_ride_month:
    path: /statistic/{year}/{month}
    defaults: { _controller: AppBundle:Statistic/MonthlyStats:listRides }

caldera_criticalmass_statistic_topten:
    path: /statistic/top
    defaults: { _controller: AppBundle:Statistic/TopStats:topStats }
