vich_uploader:
    db_driver: orm
    
    mappings:
        track_file:
            uri_prefix:         /tracks
            upload_destination: '%kernel.root_dir%/../web/tracks/'
            namer:              vich_uploader.namer_uniqid

        photo_photo:
            uri_prefix:         /photos
            upload_destination: '%kernel.root_dir%/../web/photos'
            namer:              vich_uploader.namer_uniqid

        city_photo:
            uri_prefix:         /cities
            upload_destination: '%kernel.root_dir%/../web/cities'
            namer:              vich_uploader.namer_uniqid

        ride_photo:
            uri_prefix:         /rides
            upload_destination: '%kernel.root_dir%/../web/rides'
            namer:              vich_uploader.namer_uniqid

        frontpage_teaser:
            uri_prefix:         /teaser
            upload_destination: '%kernel.root_dir%/../web/teaser'
            namer:              vich_uploader.namer_uniqid

        user_photo:
            uri_prefix:         /users
            upload_destination: '%kernel.root_dir%/../web/users'
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true
