caldera_criticalmass_city_add:
    path:  /world/{slug1}/{slug2}/{slug3}/addcity
    defaults: { _controller: AppBundle:City/CityManagement:add }

caldera_criticalmass_city_add_slug:
    path:  /{citySlug}/add
    defaults: { _controller: AppBundle:City/CityManagement:add }

caldera_criticalmass_city_edit:
    path:  /{citySlug}/edit
    defaults: { _controller: AppBundle:City/CityManagement:edit }
