caldera_criticalmass_subride_add:
    path:  /{citySlug}/{rideDate}/addsubride
    defaults: { _controller: AppBundle:Ride/Subride:add }

caldera_criticalmass_subride_edit:
    path:  /{citySlug}/{rideDate}/editsubride/{subrideId}
    defaults: { _controller: AppBundle:Ride/Subride:edit }
    
caldera_criticalmass_subride_preparecopy:
    path:  /{citySlug}/{rideDate}/preparecopysubrides
    defaults: { _controller: AppBundle:Ride/Subride:preparecopy }
    
caldera_criticalmass_subride_copy:
    path:  /{citySlug}/{rideDate}/copysubrides/{oldDate}
    defaults: { _controller: AppBundle:Ride/Subride:copy }
