facebook_login:
  path: /login/check-facebook

strava_login:
  path: /login/check-strava

criticalmass:
  resource: routes/criticalmass/routing.yml
  prefix:   /

api_controllers:
  resource: '../src/Controller/Api/'
  type: attribute
  prefix: '/api'
