gregwar_captcha_routing:
  resource: '@GregwarCaptchaBundle/Resources/config/routing/routing.yml'

criticalmass:
  resource: routes/criticalmass/routing.yml
  prefix:   /
  host:       '{host}'
  defaults:
    host: '%domain.one%'
  requirements:
    host: '%domain.one%'

criticalmass_blog:
  resource: routes/criticalmass/blog.yml
  prefix:   /
  host:       '{host}'
  defaults:
    host: '%domain.blog%'
  requirements:
    host: '%domain.blog%'

facebook_login:
  path: /login/check-facebook

strava_login:
  path: /login/check-strava

runkeeper_login:
  path: /login/check-runkeeper

twitter_login:
    path: /login/check-twitter

fos_oauth_server_token:
  resource: '@FOSOAuthServerBundle/Resources/config/routing/token.xml'

fos_oauth_server_authorize:
  path: /oauth/v2/auth
  controller: App\Controller\OAuthServer\AuthorizeController::authorizeAction
