api_timeline_yearmonth:
  path: /api/timeline/{year}/{month}
  controller: App\Controller\Api\TimelineController::yearmonthAction
  requirements:
    year: '\d{4}'
    month: '\d{2}'
  methods: GET

nelmio_api_doc:
  resource: ./routes/nelmio_api_doc.yaml

api_controllers:
  resource: ../src/Controller/Api/
  type: attribute

facebook_login:
  path: /login/check-facebook

strava_login:
  path: /login/check-strava

controllers:
  resource: ../src/Controller/
  type: attribute
  exclude: ../src/Controller/Api/

