caldera_criticalmass_api:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix: /api

caldera_criticalmass_calendar:
    resource: "@AppBundle/Resources/config/routing/calendar.yml"
    prefix: /

caldera_criticalmass_post:
    resource: "@AppBundle/Resources/config/routing/post.yml"
    prefix: /post

caldera_criticalmass_track:
    resource: "@AppBundle/Resources/config/routing/track.yml"
    prefix: /

caldera_criticalmass_frontpage:
    resource: "@AppBundle/Resources/config/routing/frontpage.yml"
    prefix: /

caldera_criticalmass_search:
    resource: "@AppBundle/Resources/config/routing/search.yml"
    prefix: /

caldera_criticalmass_board:
    resource: "@AppBundle/Resources/config/routing/board.yml"
    prefix:   /

caldera_criticalmass_help:
    resource: "@AppBundle/Resources/config/routing/help.yml"
    prefix:   /help

caldera_criticalmass_photo:
    resource: "@AppBundle/Resources/config/routing/photo.yml"
    prefix:   /

caldera_criticalmass_photogallery:
    resource: "@AppBundle/Resources/config/routing/photogallery.yml"
    prefix:   /

caldera_criticalmass_photoupload:
    resource: "@AppBundle/Resources/config/routing/photoupload.yml"
    prefix:   /

caldera_criticalmass_photomanagement:
    resource: "@AppBundle/Resources/config/routing/photomanagement.yml"
    prefix:   /

caldera_criticalmass_region:
    resource: "@AppBundle/Resources/config/routing/region.yml"
    prefix:   /

caldera_criticalmass_statistic:
    resource: "@AppBundle/Resources/config/routing/statistic.yml"
    prefix: /

caldera_criticalmass_location:
    resource: "@AppBundle/Resources/config/routing/location.yml"
    prefix: /

caldera_criticalmass_timelapse:
    resource: "@AppBundle/Resources/config/routing/timelapse.yml"
    prefix:   /

caldera_criticalmass_participation:
    resource: "@AppBundle/Resources/config/routing/participation.yml"
    prefix:   /

caldera_criticalmass_strava:
    resource: "@AppBundle/Resources/config/routing/strava.yml"
    prefix: /

caldera_criticalmass_timeline:
    resource: "@AppBundle/Resources/config/routing/timeline.yml"
    prefix: /

caldera_criticalmass_citylist:
    resource: "@AppBundle/Resources/config/routing/citylist.yml"
    prefix: /

caldera_criticalmass_city:
    resource: "@AppBundle/Resources/config/routing/city.yml"
    prefix: /

caldera_criticalmass_citymanagement:
    resource: "@AppBundle/Resources/config/routing/citymanagement.yml"
    prefix: /

caldera_criticalmass_citycycle:
    resource: "@AppBundle/Resources/config/routing/citycycle.yml"
    prefix: /

caldera_criticalmass_ride:
    resource: "@AppBundle/Resources/config/routing/ride.yml"
    prefix: /

caldera_criticalmass_ridemanagement:
    resource: "@AppBundle/Resources/config/routing/ridemanagement.yml"
    prefix: /

caldera_criticalmass_rideestimate:
    resource: "@AppBundle/Resources/config/routing/rideestimate.yml"
    prefix: /

caldera_criticalmass_subdride:
    resource: "@AppBundle/Resources/config/routing/subride.yml"
    prefix: /

caldera_criticalmass_social_network:
    resource: "@AppBundle/Resources/config/routing/social_network.yml"
    prefix: /

caldera_criticalmass_static:
    resource: "@AppBundle/Resources/config/routing/static.yml"
    prefix: /

caldera_criticalmass_redirecting:
    resource: "@AppBundle/Resources/config/routing/redirecting.yml"
    prefix: /
