caldera_criticalmass_desktop_ride_add:
    path:  /{citySlug}/add
    defaults: { _controller: CalderaCriticalmassSiteBundle:RideManagement:add }

caldera_criticalmass_desktop_ride_edit:
    path:  /{citySlug}/{rideDate}/edit
    defaults: { _controller: CalderaCriticalmassSiteBundle:RideManagement:edit }

caldera_criticalmass_ride_facebookupdate:
    path:  /{citySlug}/{rideDate}/facebookupdate
    defaults: { _controller: CalderaCriticalmassSiteBundle:RideManagement:facebookUpdate }
