caldera_frontpage:
    path:     /
    defaults: { _controller: CalderaBundle:Frontpage:index }

caldera_caldera_geobound_loadshops:
    path:     /datasource/shops
    defaults: { _controller: CalderaBundle:GeoBound:loadShops }

caldera_caldera_geobound_loadincidents:
    path:     /datasource/incidents
    defaults: { _controller: CalderaBundle:GeoBound:loadIncidents }

caldera_caldera_city_map:
    path:     /{citySlug}/map
    defaults: { _controller: CalderaBundle:Map:showCityMap }