caldera_criticalmass_city_add:
    path:  /world/{slug1}/{slug2}/{slug3}/addcity
    controller: App\Controller\City\CityManagementController::addAction

caldera_criticalmass_city_add_slug:
    path:  /{citySlug}/add
    controller: App\Controller\City\CityManagementController::addAction

caldera_criticalmass_city_edit:
    path:  /{citySlug}/edit
    controller: App\Controller\City\CityManagementController::editAction

caldera_criticalmass_city_population:
    path:  /fetch-population/{cityName}
    controller: App\Controller\City\CityManagementController::populationAction
    options:
        expose: true