caldera_criticalmass_location_show:
    path:  /{citySlug}/location/{locationSlug}
    controller: App\Controller\LocationController::showAction

caldera_criticalmass_location_ride:
    path:  /{citySlug}/{rideIdentifier}/location
    controller: App\Controller\LocationController::rideAction
