caldera_criticalmass_photo_ajaxview:
    path: /{citySlug}/{rideIdentifier}/ajaxphotoview
    controller: App\Controller\Photo\PhotoController::ajaxphotoviewAction

caldera_criticalmass_photo_show_ride:
    path: /{citySlug}/{rideIdentifier}/photo/{id}
    controller: App\Controller\Photo\PhotoController::showAction

caldera_criticalmass_photo_show:
    path: /photo/{id}
    controller: App\Controller\Photo\PhotoController::showAction
    options:
        expose: true
