caldera_criticalmass_timeline_post_write:
    path:     /write
    controller: App\Controller\PostController::writeAction

caldera_criticalmass_timeline_post_write_ride:
    path:     /write/ride/{rideId}
    controller: App\Controller\PostController::writeRideAction

caldera_criticalmass_timeline_post_write_city:
    path:     /write/city/{cityId}
    controller: App\Controller\PostController::writeCityAction

caldera_criticalmass_timeline_post_write_photo:
    path:     /write/photo/{photoId}
    controller: App\Controller\PostController::writePhotoAction

caldera_criticalmass_timeline_post_write_thread:
    path:     /write/thread/{threadId}
    controller: App\Controller\PostController::writeThreadAction

caldera_criticalmass_timeline_post_write_blogpost:
    path:     /write/blogpost/{blogPostId}
    controller: App\Controller\PostController::writeBlogPostAction
