caldera_criticalmass_ride_show:
    path:  /{citySlug}/{rideIdentifier}
    controller: App\Controller\Ride\RideController::showAction
    options:
        expose: true

caldera_criticalmass_ride_ical:
    path:  /{citySlug}/{rideIdentifier}/ical
    controller: App\Controller\Ride\CalendarController::icalAction

