caldera_criticalmass_heatmap:
    resource: 'heatmap.yml'
    prefix: /

caldera_criticalmass_trackmassimport:
    resource: 'track_mass_import.yml'
    prefix: /

caldera_criticalmass_profile:
    resource: 'profile.xml'
    prefix: /

caldera_criticalmass_api:
    resource: 'api.yml'
    prefix: /api

caldera_criticalmass_calendar:
    resource: 'calendar.yml'
    prefix: /

caldera_criticalmass_post:
    resource: 'post.yml'
    prefix: /post

caldera_criticalmass_track:
    resource: 'track.yml'
    prefix: /

caldera_criticalmass_search:
    resource: 'search.yml'
    prefix: /

caldera_criticalmass_blog:
    resource: 'blog.yml'
    prefix:   /
    host:       '{host}'
    defaults:
        host: '%domain.blog%'
    requirements:
        host: '%domain.blog%'

caldera_criticalmass_frontpage:
    resource: 'frontpage.yml'
    prefix: /
    
caldera_criticalmass_board:
    resource: 'board.yml'
    prefix:   /

caldera_criticalmass_help:
    resource: 'help.yml'
    prefix:   /help

caldera_criticalmass_photo:
    resource: 'photo.yml'
    prefix:   /

caldera_criticalmass_photo_export:
    resource: 'photoexport.yml'
    prefix:   /

caldera_criticalmass_photogallery:
    resource: 'photogallery.yml'
    prefix:   /

caldera_criticalmass_photoupload:
    resource: 'photoupload.yml'
    prefix:   /

caldera_criticalmass_photomanagement:
    resource: 'photomanagement.yml'
    prefix:   /

caldera_criticalmass_region:
    resource: 'region.yml'
    prefix:   /

caldera_criticalmass_statistic:
    resource: 'statistic.yml'
    prefix: /

caldera_criticalmass_location:
    resource: 'location.yml'
    prefix: /

caldera_criticalmass_timelapse:
    resource: 'timelapse.yml'
    prefix:   /

caldera_criticalmass_participation:
    resource: 'participation.yml'
    prefix:   /

caldera_criticalmass_strava:
    resource: 'strava.yml'
    prefix: /

caldera_criticalmass_timeline:
    resource: 'timeline.yml'
    prefix: /

caldera_criticalmass_citylist:
    resource: 'citylist.yml'
    prefix: /

caldera_criticalmass_city:
    resource: 'city.yml'
    prefix: /

caldera_criticalmass_citymanagement:
    resource: 'citymanagement.yml'
    prefix: /

caldera_criticalmass_citycycle:
    resource: 'citycycle.yml'
    prefix: /

caldera_criticalmass_social_network:
    resource: 'social_network.yml'
    prefix: /

caldera_criticalmass_static:
    resource: 'static.yml'
    prefix: /

caldera_criticalmass_ridemanagement:
    resource: 'ridemanagement.yml'
    prefix: /

caldera_criticalmass_ride:
    resource: 'ride.yml'
    prefix: /

caldera_criticalmass_rideestimate:
    resource: 'rideestimate.yml'
    prefix: /

caldera_criticalmass_subdride:
    resource: 'subride.yml'
    prefix: /

#caldera_criticalmass_redirecting:
#    resource: 'redirecting.yml'
#    prefix: /
