caldera_criticalmass_profile:
    resource: 'profile.xml'
    prefix: /

caldera_criticalmass_post:
    resource: 'post.yml'
    prefix: /post

caldera_criticalmass_track:
    resource: 'track.yml'
    prefix: /

caldera_criticalmass_frontpage:
    resource: 'frontpage.yml'
    prefix: /

caldera_criticalmass_photo:
    resource: 'photo.yml'
    prefix:   /

caldera_criticalmass_photo_export:
    resource: 'photoexport.yml'
    prefix:   /

caldera_criticalmass_photogallery:
    resource: 'photogallery.yml'
    prefix:   /

caldera_criticalmass_photoupload:
    resource: 'photoupload.yml'
    prefix:   /

caldera_criticalmass_photomanagement:
    resource: 'photomanagement.yml'
    prefix:   /

caldera_criticalmass_region:
    resource: 'region.yml'
    prefix:   /

caldera_criticalmass_statistic:
    resource: 'statistic.yml'
    prefix: /

caldera_criticalmass_timelapse:
    resource: 'timelapse.yml'
    prefix:   /

caldera_criticalmass_participation:
    resource: 'participation.yml'
    prefix:   /

caldera_criticalmass_strava:
    resource: 'strava.yml'
    prefix: /

caldera_criticalmass_timeline:
    resource: 'timeline.yml'
    prefix: /

caldera_criticalmass_citylist:
    resource: 'citylist.yml'
    prefix: /

caldera_criticalmass_citymanagement:
    resource: 'citymanagement.yml'
    prefix: /

caldera_criticalmass_citycycle:
    resource: 'citycycle.yml'
    prefix: /

caldera_criticalmass_social_network:
    resource: 'social_network.yml'
    prefix: /

caldera_criticalmass_static:
    resource: 'static.yml'
    prefix: /

caldera_criticalmass_ridemanagement:
    resource: 'ridemanagement.yml'
    prefix: /

caldera_criticalmass_ride:
    resource: 'ride.yml'
    prefix: /

caldera_criticalmass_oauth:
    resource: 'oauth.yml'
    prefix: /


#caldera_criticalmass_redirecting:
#    resource: 'redirecting.yml'
#    prefix: /
