caldera_criticalmass_profile:
    resource: 'profile.xml'
    prefix: /

caldera_criticalmass_photo:
    resource: 'photo.yml'
    prefix:   /

caldera_criticalmass_photo_export:
    resource: 'photoexport.yml'
    prefix:   /

caldera_criticalmass_photogallery:
    resource: 'photogallery.yml'
    prefix:   /

caldera_criticalmass_photoupload:
    resource: 'photoupload.yml'
    prefix:   /

caldera_criticalmass_photomanagement:
    resource: 'photomanagement.yml'
    prefix:   /

caldera_criticalmass_statistic:
    resource: 'statistic.yml'
    prefix: /

caldera_criticalmass_timelapse:
    resource: 'timelapse.yml'
    prefix:   /

caldera_criticalmass_participation:
    resource: 'participation.yml'
    prefix:   /

caldera_criticalmass_timeline:
    resource: 'timeline.yml'
    prefix: /

caldera_criticalmass_citylist:
    resource: 'citylist.yml'
    prefix: /

caldera_criticalmass_citymanagement:
    resource: 'citymanagement.yml'
    prefix: /

caldera_criticalmass_social_network:
    resource: 'social_network.yml'
    prefix: /

caldera_criticalmass_static:
    resource: 'static.yml'
    prefix: /

caldera_criticalmass_ride:
    resource: 'ride.yml'
    prefix: /

caldera_criticalmass_oauth:
    resource: 'oauth.yml'
    prefix: /
