caldera_criticalmass_profile:
    resource: 'profile.xml'
    prefix: /

caldera_criticalmass_social_network:
    resource: 'social_network.yml'
    prefix: /

caldera_criticalmass_static:
    resource: 'static.yml'
    prefix: /
