caldera_criticalmass_profile:
    resource: 'profile.xml'
    prefix: /

caldera_criticalmass_photogallery:
    resource: 'photogallery.yml'
    prefix:   /

caldera_criticalmass_photomanagement:
    resource: 'photomanagement.yml'
    prefix:   /

caldera_criticalmass_statistic:
    resource: 'statistic.yml'
    prefix: /

caldera_criticalmass_timeline:
    resource: 'timeline.yml'
    prefix: /

caldera_criticalmass_social_network:
    resource: 'social_network.yml'
    prefix: /

caldera_criticalmass_static:
    resource: 'static.yml'
    prefix: /

caldera_criticalmass_ride:
    resource: 'ride.yml'
    prefix: /

caldera_criticalmass_oauth:
    resource: 'oauth.yml'
    prefix: /
