caldera_criticalmass_subride_add:
    path:  /{citySlug}/{rideIdentifier}/addsubride
    controller: App\Controller\Ride\SubrideController::addAction

caldera_criticalmass_subride_edit:
    path:  /{citySlug}/{rideIdentifier}/editsubride/{subrideId}
    controller: App\Controller\Ride\SubrideController::editAction
    
caldera_criticalmass_subride_preparecopy:
    path:  /{citySlug}/{rideIdentifier}/preparecopysubrides
    controller: App\Controller\Ride/SubrideController::preparecopyAction
    
caldera_criticalmass_subride_copy:
    path:  /{citySlug}/{rideIdentifier}/copysubrides/{newDate}
    controller: App\Controller\Ride\SubrideController::copyAction
