caldera_criticalmass_timelapse_homepage:
    path:     /{citySlug}/{rideIdentifier}/timelapse
    controller: App\Controller\Ride\TimelapseController::showAction

caldera_criticalmass_timelapse_load:
    path:     /{citySlug}/{rideIdentifier}/timelapse/load/{trackId}
    controller: App\Controller\Ride\TimelapseController::loadtrackAction
    options:
        expose: true
